vaadin.launch-browser=true
spring.application.name=quiz-rooms
vaadin.allowed-packages=com.vaadin,org.vaadin,com.flowingcode,com.example
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=YOUR_DB_USERNAME
spring.datasource.url=jdbc:postgresql://localhost:5432/YOUR_DB_NAME
spring.datasource.password=YOUR_DB_PASSWORD
#spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.sql.init.mode=always
spring.sql.init.platform=postgres
spring.jpa.defer-datasource-initialization=true
spring.main.allow-bean-definition-overriding=true
spring.jpa.properties.hibernate.jdbc.batch_size=100
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true
spring.main.allow-circular-references=true
vaadin.pushMode=automatic

# Spring AI - openai config for open router
spring.ai.openai.api-key=YOUR_OPEN_ROUTER_API_KEY
spring.ai.openai.base-url=https://openrouter.ai/api
#You can use any other model
spring.ai.openai.chat.options.model=openai/gpt-4o-mini

