vaadin.launch-browser=true
spring.application.name=quiz-rooms
vaadin.allowed-packages=com.vaadin,org.vaadin,com.flowingcode,com.example
spring.datasource.driver-class-name=org.postgresql.Driver
#spring.datasource.username=postgres
#spring.datasource.url=jdbc:postgresql://localhost:5432/quiz-rooms
#spring.datasource.password=Postgrejdbcpk
spring.datasource.username=postgres
spring.datasource.url=jdbc:postgresql://98.92.245.101/quiz-rooms-db
spring.datasource.password=Postgres123
spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.sql.init.mode=always
spring.sql.init.platform=postgres
spring.jpa.defer-datasource-initialization=true
spring.main.allow-bean-definition-overriding=true
spring.jpa.properties.hibernate.jdbc.batch_size=100
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true
spring.main.allow-circular-references=true
vaadin.pushMode=automatic

# Spring AI - openai config for open router
spring.ai.openai.api-key=YOUR_OPENAI_API_KEY from open router
spring.ai.openai.base-url=https://openrouter.ai/api
spring.ai.openai.chat.options.model=CHAT_MODEL

